// agent_scope_guard.js - Live-page scope checks without cross-tab destructive cleanup.
(() => {
    'use strict';
    if(!chrome?.runtime?.id)return;
    const store=window.ScopedConversationStore||null,CURRENT_CONTEXT_KEY='current_context';
    let lastLiveConvo=getLiveConversationId(),contextSyncTimer=null;
    const id=v=>v===null||v===undefined?'':String(v).trim();
    function pathOf(urlValue=location.href){try{return new URL(urlValue,location.href).pathname||'/';}catch(_){return location.pathname||'/';}}
    function getPageIdentity(urlValue=location.href){const pathname=pathOf(urlValue),conversationId=pathname.match(/^\/messages\/(\d+)/)?.[1]||null,editor=pathname.match(/^\/your\/shops\/me\/listing-editor\/edit\/(\d+)/)?.[1]||null,pub=pathname.match(/^\/listing\/(\d+)/)?.[1]||null;let pageKind='other';if(conversationId)pageKind='messages';else if(/^\/messages(?:\/|$)/.test(pathname))pageKind='messages-inbox';else if(editor)pageKind='listing-editor';else if(pub)pageKind='public-listing';else if(/^\/your\/shops\/me(?:\/|$)/.test(pathname))pageKind='shop-dashboard';return{pathname,conversationId,listingId:editor||pub||null,pageKind,pageKey:`${pageKind}:${pathname}`};}
    function getLiveConversationId(){return getPageIdentity(location.href).conversationId;}
    function contextUrl(context){return context?.metadata?.url||context?.page_url||context?.page_content?.metadata?.url||'';}
    function contextMatchesLive(context){const url=contextUrl(context);return!!url&&getPageIdentity(url).pageKey===getPageIdentity(location.href).pageKey;}
    function historyMatchesLive(history){const live=getLiveConversationId();return!!live&&id(history?.convo_id||history?.conversation_id)===live;}
    async function get(keys){try{return await chrome.storage.local.get(keys);}catch(e){console.warn('AgentScopeGuard: storage read failed',e);return{};}}
    async function set(values){try{await chrome.storage.local.set(values);return true;}catch(e){console.warn('AgentScopeGuard: storage write failed',e);return false;}}

    function directListingId(detail){for(const v of[detail?.listing_id,detail?.listingId,detail?.listing?.listing_id,detail?.listing?.listingId,detail?.transaction?.listing_id,detail?.transaction?.listingId,detail?.receipt_history?.[0]?.transactions?.[0]?.listing_id,detail?.receipt_history?.[0]?.transactions?.[0]?.listingId]){const m=id(v).match(/\d{5,}/);if(m)return m[0];}return null;}
    function transactionId(detail){return id(detail?.transaction?.transaction_id||detail?.transaction_id||detail?.receipt_history?.[0]?.transactions?.[0]?.transaction_id)||null;}
    async function setScopedListing(convoId,listingId){if(!convoId||!listingId||getLiveConversationId()!==String(convoId))return false;if(store)return store.setListing(convoId,listingId,{updatedAt:Date.now()});await set({ETSY_CURRENT_LISTING_ID:String(listingId),ETSY_CURRENT_LISTING_SCOPE:{convoId:String(convoId),listingId:String(listingId),updatedAt:Date.now()}});return true;}
    async function resolveListingFromTransaction(txId,convoId){if(!txId||!convoId)return null;try{const response=await fetch(`https://www.etsy.com/transaction/${encodeURIComponent(txId)}`,{credentials:'include',redirect:'follow'}),listing=response?.url?.match(/\/listing\/(\d+)/)?.[1]||null;if(!listing||getLiveConversationId()!==String(convoId))return null;await setScopedListing(convoId,listing);return listing;}catch(e){console.debug('AgentScopeGuard: transaction resolution skipped',e?.message||e);return null;}}
    async function bindListingScopeFromDetail(data){const detail=data?.detail,live=getLiveConversationId(),convo=id(detail?.conversation_id);if(!detail||!live||convo!==live)return false;const listing=directListingId(detail);if(listing)return setScopedListing(live,listing);const tx=transactionId(detail);if(tx)resolveListingFromTransaction(tx,live);return false;}
    async function getScopedListingId(){const page=getPageIdentity(location.href);if(page.listingId)return page.listingId;if(!page.conversationId)return null;if(store)return(await store.getListing(page.conversationId))?.listingId||null;const s=await get(['ETSY_CURRENT_LISTING_ID','ETSY_CURRENT_LISTING_SCOPE']),listing=id(s.ETSY_CURRENT_LISTING_ID),scope=s.ETSY_CURRENT_LISTING_SCOPE;return listing&&id(scope?.convoId)===page.conversationId&&id(scope?.listingId)===listing?listing:null;}

    function buildFreshPageContext(){try{const page=window.PageParser?.getFullPageData?.();if(!page)return null;return{page_content:{title:page.title,markdown:page.markdown,excerpt:page.excerpt,siteName:page.siteName,hasContent:page.hasContent},metadata:page.metadata,page_url:location.href};}catch(e){return null;}}
    function installFreshContextGuard(){const original=window.EtsyAI_GetFreshContext;if(typeof original!=='function'||original.__etsyScopeGuarded)return;const guarded=function(){const cached=original();if(cached&&contextMatchesLive(cached))return cached;return buildFreshPageContext()||null;};guarded.__etsyScopeGuarded=true;window.EtsyAI_GetFreshContext=guarded;}
    async function syncFreshContext(){const fresh=buildFreshPageContext();if(!fresh||!contextMatchesLive(fresh))return false;await set({[CURRENT_CONTEXT_KEY]:fresh});return true;}
    function scheduleFreshContext(){if(contextSyncTimer)clearTimeout(contextSyncTimer);contextSyncTimer=setTimeout(()=>{contextSyncTimer=null;syncFreshContext();},100);}

    function emptyImageMetadata(){return{imageIntelCount:0,imageIntelCustomerCount:0,imageIntelOwnerCount:0,imageIntelUnknownRoleCount:0,imageIntelAvailableCount:0,imageIntelFailedCount:0,imageIntelOversizedCount:0,imageIntelDeferredCount:0,imageIntelPendingCount:0,imageIntelCoverage:0,imageIntelAnalyzedThisRequest:0,imageIntelQueuedThisRequest:0,imageIntelBatchCallsThisRequest:0,imageIntelErrors:[]};}
    function patchImage(){const manager=window.ImageIntelligenceManager;if(!manager||manager.__etsyScopeGuarded)return;const analyze=manager.analyzeCurrentCustomerImages.bind(manager),build=manager.buildContextSection.bind(manager),metadata=manager.getMetadata.bind(manager);manager.analyzeCurrentCustomerImages=async function(...args){const live=getLiveConversationId(),history=store?await store.getHistory(live):(await get(['ETSY_CHAT_HISTORY'])).ETSY_CHAT_HISTORY;if(!historyMatchesLive(history))return emptyImageMetadata();return analyze(...args);};manager.buildContextSection=async function(...args){const live=getLiveConversationId(),history=store?await store.getHistory(live):(await get(['ETSY_CHAT_HISTORY'])).ETSY_CHAT_HISTORY;if(!historyMatchesLive(history))return'';return build(...args);};manager.getMetadata=function(...args){if(lastLiveConvo!==getLiveConversationId())return emptyImageMetadata();return metadata(...args);};manager.__etsyScopeGuarded=true;}

    function patchSummaryQueue(){const manager=window.ConversationContextManager;if(!manager||manager.__etsyWriteSerialized)return;const cached=manager.getCachedSummary.bind(manager),precompute=manager.precomputeSummary.bind(manager);let queue=Promise.resolve();const tasks=new Map();function key(history,omitted){const convo=id(history?.convo_id);if(!convo||!omitted?.length)return'';let text=`${convo}|${omitted.length}`;for(const item of omitted){const m=item?.message||item||{};text+=`|${item?.sourceIndex??''}:${m.message_id||m.convo_message_id||m.id||''}:${m.create_date||''}:${m.message_body||m.message||m.body||m.text||''}`;}let hash=0xcbf29ce484222325n,prime=0x100000001b3n,mask=0xffffffffffffffffn;for(let i=0;i<text.length;i++){hash^=BigInt(text.charCodeAt(i));hash=(hash*prime)&mask;}return`${convo}:${hash.toString(36)}`;}function enqueue(history,omitted){const k=key(history,omitted);if(!k)return Promise.resolve('');if(tasks.has(k))return tasks.get(k);const task=queue.catch(()=>undefined).then(()=>precompute(history,omitted));queue=task.then(()=>undefined,()=>undefined);tasks.set(k,task);task.finally(()=>{if(tasks.get(k)===task)tasks.delete(k);});return task;}manager.precomputeSummary=enqueue;manager.getOrCreateSummary=async function(history,omitted,options={}){const ready=await cached(history,omitted);if(ready)return ready;const task=enqueue(history,omitted),requested=Number(options.maxWaitMs),wait=Number.isFinite(requested)?Math.max(0,Math.min(requested,10000)):Number(manager.DEFAULT_FOREGROUND_WAIT_MS||1200);if(wait<=0)return'';return new Promise(resolve=>{let done=false;const timer=setTimeout(()=>{if(done)return;done=true;resolve('');},wait);task.then(summary=>{if(done)return;done=true;clearTimeout(timer);resolve(summary||'');},()=>{if(done)return;done=true;clearTimeout(timer);resolve('');});});};manager.__etsyWriteSerialized=true;}

    async function onNavigation(){lastLiveConvo=getLiveConversationId();installFreshContextGuard();scheduleFreshContext();}
    window.addEventListener('message',event=>{if(event.source!==window||event.data?.source!=='etsy-page-interceptor'||event.data?.type!=='ETSY_DETAIL_VIEW_DATA')return;const detailConvo=id(event.data.data?.detail?.conversation_id),live=getLiveConversationId();if(live&&detailConvo===live&&!window.EtsyContextInterceptor)bindListingScopeFromDetail(event.data.data).catch(()=>{});});
    window.addEventListener('etsy-ai-locationchange',onNavigation);window.addEventListener('popstate',onNavigation);window.addEventListener('hashchange',onNavigation);
    installFreshContextGuard();patchImage();patchSummaryQueue();scheduleFreshContext();
    window.EtsyAgentScopeGuard={getPageIdentity,contextMatchesLive,historyMatchesLive,getScopedListingId,buildFreshPageContext,bindListingScopeFromDetail,resolveListingFromTransaction,clearStaleScopedState:async()=>true};
})();
