// agent_management_gate.js - Local-first management routing for memory and saved quick replies.
(() => {
    'use strict';
    if(!window.AIServiceFactory||window.__ETSY_AI_MANAGEMENT_GATE__)return;window.__ETSY_AI_MANAGEMENT_GATE__=true;
    const MANAGEMENT_PROMPT_MARKER="Classify whether the Owner's latest turn is an explicit request to manage assistant memory or reusable Etsy quick replies.",MEMORY_DECISION_PROMPT_MARKER="You classify the Owner's reply to a pending memory confirmation.";
    let memoryConfirmationStale=false;
    const normalized=v=>String(v||'').trim().replace(/[’ʼ`]/g,"'");
    function result(domain='none',action='none',fields={}){return JSON.stringify({domain,action,text:fields.text||'',keyword:fields.keyword||'',target:fields.target||'',label:fields.label||'',confidence:fields.confidence??1});}
    const noneClassification=()=>result('none','none'),memoryDecision=(decision,confidence=1)=>JSON.stringify({decision,confidence});
    function stripTail(v){return normalized(v).replace(/^[\s:,.\-–—]+/,'').replace(/^(?:that|this|що|шо|что)\s+/i,'').replace(/^(?:for\s+future(?:\s+replies)?|на\s+майбутнє|на\s+будущее)\s*[:,-]?\s*/iu,'').trim();}
    function deterministicManagementIntent(text){const value=normalized(text);if(!value)return null;if(/^(?:please\s+)?(?:clear|erase|delete)\s+(?:all\s+)?(?:my\s+)?memory\s*[.!]?$/i.test(value)||/^(?:очисти|видали|стерти|зітри)\s+(?:всю\s+)?пам['']?ять\s*[.!]?$/iu.test(value)||/^(?:очисти|удали|сотри)\s+(?:всю\s+)?память\s*[.!]?$/iu.test(value))return result('memory','clear');for(const p of[/^(?:please\s+)?remember\b([\s\S]*)$/i,/^(?:(?:can|could|would)\s+you\s+remember)\b([\s\S]*)$/i,/^(?:please\s+)?(?:save|store)\s+(?:this\s+)?(?:to|in)\s+(?:your\s+)?memory\b([\s\S]*)$/i,/^(?:запам['']?ятай|запамятай)\b([\s\S]*)$/iu,/^(?:збережи|додай)\s+(?:це\s+)?(?:в|до)\s+пам['']?ят(?:ь|і)\b([\s\S]*)$/iu,/^(?:запомни)\b([\s\S]*)$/iu,/^(?:сохрани|добавь)\s+(?:это\s+)?(?:в|в\s+мою)\s+память\b([\s\S]*)$/iu]){const m=value.match(p);if(!m)continue;const body=stripTail(m[1]);if(!body||/^(?:what|when|where|who|why|how)\b/i.test(body))return null;return result('memory','add',{text:body});}for(const p of[/^(?:please\s+)?forget\b([\s\S]*)$/i,/^(?:please\s+)?(?:remove|delete)\s+(.+?)\s+from\s+(?:your\s+)?memory\s*[.!]?$/i,/^(?:забудь)\b([\s\S]*)$/iu,/^(?:видали|прибери)\s+(.+?)\s+(?:з|із)\s+пам['']?ят(?:і|и)\s*[.!]?$/iu,/^(?:удали|убери)\s+(.+?)\s+из\s+памяти\s*[.!]?$/iu]){const m=value.match(p);if(!m)continue;const keyword=stripTail(m[1]);if(keyword)return result('memory','remove',{keyword,text:keyword});}if(/^(?:show|list)\s+(?:my\s+)?(?:saved\s+)?quick\s*repl(?:y|ies)\s*[.!]?$/i.test(value)||/^(?:покажи|покажи мені|список)\s+(?:збережен\w+\s+)?(?:швидк\w+\s+)?(?:відповід\w+|репл\w+)\s*[.!]?$/iu.test(value)||/^(?:покажи|список)\s+(?:сохраненн\w+\s+)?(?:быстр\w+\s+)?(?:ответ\w+|репл\w+)\s*[.!]?$/iu.test(value))return result('quick_reply','list');return null;}
    function looksLikeExplicitManagement(text){if(deterministicManagementIntent(text))return true;const v=normalized(text).toLowerCase();if(!v)return false;if([/\bmemory\b.{0,80}\b(add|save|store|remove|delete|clear|forget|update)\b/i,/\b(forget|clear|delete|remove)\b.{0,80}\b(memory|remembered|saved fact|preference)\b/i,/(пам['']?ят|памят).{0,80}(збереж|дод|видал|очист|забуд|сохран|удал|запом)/iu].some(p=>p.test(v)))return true;return/(quick\s*repl(?:y|ies)|saved\s+repl(?:y|ies)|reply\s+template|швидк\w*\s+(?:відпов|репл)|шаблон\w*\s+(?:відпов|репл)|быстр\w*\s+(?:ответ|репл)|шаблон\w*\s+(?:ответ|репл))/iu.test(v);}
    function extractReply(raw){const text=normalized(raw);try{const parsed=JSON.parse(text);if(typeof parsed?.ownerReply==='string')return normalized(parsed.ownerReply);}catch(_){}return text;}
    function deterministicMemoryDecision(raw){const v=extractReply(raw).toLowerCase();if(!v)return memoryDecision('unclear');if(/^(?:yes|yep|yeah|ok|okay|sure|confirm|confirmed|proceed|do it|go ahead|remove them|remove all|clear it|clear all|так|ага|так,?\s*(?:давай|роби|видаляй|очищай)?|звісно|добре|да|ага|да,?\s*(?:давай|делай|удаляй|очищай)?)\s*[.!]?$/iu.test(v))return memoryDecision('accept');if(/^(?:no|nope|cancel|stop|leave it|leave memory unchanged|don't|do not|ні|не треба|скасуй|залиш як є|нет|не надо|отмена|оставь как есть)\s*[.!]?$/iu.test(v))return memoryDecision('reject');return memoryDecision('unclear');}
    function parse(raw){try{return JSON.parse(String(raw||'').replace(/^```json\s*/i,'').replace(/^```\s*/i,'').replace(/```\s*$/i,'').trim());}catch(_){return null;}}
    function normalizeClassifierResult(raw){const p=parse(raw);return p?.action==='offer'?noneClassification():String(raw||'').trim();}
    function arm(raw){const p=parse(raw);if(p?.domain==='memory'&&['clear','remove'].includes(p.action))memoryConfirmationStale=false;}
    function emit(params,raw){params.onChunk?.(raw,raw);params.onComplete?.(raw);return raw;}
    function wrapService(service){if(!service||service.__etsyManagementGated||typeof service.streamMessage!=='function')return service;const original=service.streamMessage.bind(service);service.streamMessage=async function(params={}){const system=String(params.systemInstruction||''),owner=[...(params.messages||[])].reverse().find(m=>m?.role==='user')?.content||'';if(system.includes(MEMORY_DECISION_PROMPT_MARKER)){if(memoryConfirmationStale)return emit(params,memoryDecision('unclear'));const raw=deterministicMemoryDecision(owner),decision=parse(raw)?.decision||'unclear';if(decision==='unclear')memoryConfirmationStale=true;return emit(params,raw);}if(!system.includes(MANAGEMENT_PROMPT_MARKER))return original(params);const deterministic=deterministicManagementIntent(owner);if(deterministic){arm(deterministic);return emit(params,deterministic);}if(!looksLikeExplicitManagement(owner))return emit(params,noneClassification());let captured='';const value=await original({...params,systemInstruction:`${system}\n\nIMPORTANT: action=offer is disabled. Return domain=none/action=none unless the Owner explicitly asked to manage persistent memory or saved quick replies.`,onChunk:(_chunk,full)=>{captured=full||captured;},onComplete:full=>{captured=full||captured;}}),output=normalizeClassifierResult(captured||value||'');arm(output);return emit(params,output);};service.__etsyManagementGated=true;return service;}
    const originalGet=window.AIServiceFactory.getCurrentService.bind(window.AIServiceFactory);window.AIServiceFactory.getCurrentService=async function(...args){return wrapService(await originalGet(...args));};window.EtsyAgentManagementGate={looksLikeExplicitManagement,deterministicManagementIntent,deterministicMemoryDecision,noneClassification,normalizeClassifierResult,isMemoryConfirmationStale:()=>memoryConfirmationStale};
})();
