// agent_context_manager.js - Compact deterministic orientation for the active Etsy scope.
(() => {
    'use strict';
    if(!window.BaseAIService)return;
    const ACTIVE_FACTS_KEY='ETSY_AI_ACTIVE_CONTEXT_FACTS',LISTING_SCOPE_KEY='ETSY_CURRENT_LISTING_SCOPE',MAX_ASSISTANT_HISTORY_MESSAGES=32,FIRST_ASSISTANT_HISTORY_MESSAGES=6,MAX_ASSISTANT_MESSAGE_CHARS=4000,MAX_SNAPSHOT_MESSAGE_CHARS=1200;
    const trimText=(value,max=MAX_SNAPSHOT_MESSAGE_CHARS)=>{const text=String(value||'').replace(/\s+/g,' ').trim();return!text?'':text.length>max?`${text.slice(0,max).trim()}…`:text;};
    const liveConvo=()=>location.pathname.match(/^\/messages\/(\d+)/)?.[1]||null;
    const body=m=>trimText(m?.message_body||m?.message||m?.body||m?.text||'');
    const senderId=m=>String(m?.sender_user_id||m?.sender_id||m?.user_id||m?.from_user_id||'').trim();
    function role(m,h){const s=senderId(m),customer=String(h?.customer_user_id||'').trim();if(customer&&s)return customer===s?'CUSTOMER':'OWNER';const rt=`${m?.sender_type||''} ${m?.role||''} ${m?.author_role||''}`.toLowerCase();if(/\b(buyer|customer)\b/.test(rt))return'CUSTOMER';if(/\b(seller|shop|owner|merchant)\b/.test(rt))return'OWNER';if(m?.is_customer===true)return'CUSTOMER';if(m?.is_seller===true||m?.is_shop_member===true||m?.from_owner===true)return'OWNER';const cn=trimText(h?.customer_display_name||'',100).toLowerCase(),sn=trimText(m?.sender_display_name||m?.sender_name||'',100).toLowerCase();return cn&&sn&&cn===sn?'CUSTOMER':'PARTICIPANT';}
    function timeMs(m){const v=m?.create_date??m?.created_at??m?.timestamp??0,n=Number(v);if(Number.isFinite(n)&&n>0)return n<10_000_000_000?n*1000:n;const p=Date.parse(String(v||''));return Number.isFinite(p)?p:0;}
    function stamp(m){const ms=timeMs(m);if(!ms)return'';try{return new Date(ms).toLocaleString();}catch(_){return'';}}
    function attachmentCount(m){if(Array.isArray(m?.attachments))return m.attachments.length;if(Array.isArray(m?.images))return m.images.length;return m?.has_images?1:0;}
    async function get(keys){if(!chrome.runtime?.id)return{};try{return await chrome.storage.local.get(keys);}catch(e){console.warn('AgentContext: storage read failed',e);return{};}}
    async function set(values){if(!chrome.runtime?.id)return false;try{await chrome.storage.local.set(values);return true;}catch(e){console.warn('AgentContext: storage write failed',e);return false;}}
    async function readHistory(convoId){if(window.ScopedConversationStore)return window.ScopedConversationStore.getHistory(convoId);const s=await get(['ETSY_CHAT_HISTORY']),h=s.ETSY_CHAT_HISTORY;return String(h?.convo_id||'')===String(convoId)?h:null;}
    async function readFacts(convoId){if(window.ScopedConversationStore)return window.ScopedConversationStore.getFacts(convoId);const s=await get([ACTIVE_FACTS_KEY]),f=s[ACTIVE_FACTS_KEY];return String(f?.convoId||'')===String(convoId)?f:null;}
    async function writeFacts(facts){if(window.ScopedConversationStore)return window.ScopedConversationStore.setFacts(facts);return set({[ACTIVE_FACTS_KEY]:facts});}
    async function readListingId(convoId){if(window.ScopedConversationStore)return(await window.ScopedConversationStore.getListing(convoId))?.listingId||null;if(window.EtsyAgentScopeGuard?.getScopedListingId)return window.EtsyAgentScopeGuard.getScopedListingId();const s=await get(['ETSY_CURRENT_LISTING_ID',LISTING_SCOPE_KEY]),listing=String(s.ETSY_CURRENT_LISTING_ID||'').trim(),scope=s[LISTING_SCOPE_KEY];return listing&&String(scope?.convoId||'')===String(convoId)&&String(scope?.listingId||'')===listing?listing:null;}
    function latestByRole(messages,h,wanted){for(let i=messages.length-1;i>=0;i--)if(role(messages[i],h)===wanted)return messages[i];return null;}
    function format(label,m){if(!m)return`${label}: none available`;const sender=trimText(m.sender_display_name||m.sender_name||'',80),time=stamp(m),text=body(m),attachments=attachmentCount(m);return`${label}${sender?` (${sender})`:''}${time?` [${time}]`:''}: ${text||'[no text]'}${attachments?` [${attachments} attachment(s)]`:''}`;}
    async function buildActiveContextSnapshot(){
        const convoId=liveConvo();if(!convoId)return'';const[history,facts,listingId]=await Promise.all([readHistory(convoId),readFacts(convoId),readListingId(convoId)]),stored=String(history?.convo_id||'').trim(),matches=!!history?.messages?.length&&stored===String(convoId);let out='\n\n### ACTIVE_CONTEXT_SNAPSHOT\n(Deterministic orientation for the live Etsy conversation. Use as an index only; direct conversation/listing/image evidence is authoritative. Never borrow facts from another conversation.)\n';out+=`Live conversation: convo_id=${convoId}\n`;if(!matches){out+=`Conversation data: not ready or mismatched (stored=${stored||'none'}). Treat customer/order/listing/image facts as unavailable until live scope is hydrated.\n`;return out;}
        const messages=history.messages||[],latestCustomer=latestByRole(messages,history,'CUSTOMER'),latestOwner=latestByRole(messages,history,'OWNER'),latest=messages[messages.length-1]||null,latestRole=latest?role(latest,history):'UNKNOWN',customerName=trimText(history.customer_display_name||'',100)||'unknown',timestamp=Number(history.timestamp||0),age=timestamp?Math.max(0,Date.now()-timestamp):0,totalAttachments=messages.reduce((sum,m)=>sum+attachmentCount(m),0);
        out+=`Customer: ${customerName}\nConversation messages: ${messages.length}; context age: ${timestamp?BaseAIService.INSTRUCTIONS.formatAge(age):'unknown'}; latest speaker: ${latestRole}\n${format('Latest CUSTOMER message',latestCustomer)}\n${format('Latest OWNER Etsy message',latestOwner)}\nStructured conversation attachments: ${totalAttachments}\n`;
        if(listingId){const s=await get([`RAG_LISTING_${listingId}`]),listing=s[`RAG_LISTING_${listingId}`];out+=`Active listing: listing_id=${listingId}${listing?.title?` — ${trimText(listing.title,220)}`:' (details not cached yet)'}\n`;}else out+='Active listing: unresolved for this conversation; do not reuse a listing from another conversation.\n';
        if(facts?.receiptId)out+=`Current receipt: ${facts.receiptId}\n`;if(facts?.transactionIds?.length)out+=`Current transaction id(s): ${facts.transactionIds.join(', ')}\n`;
        const vm=window.ImageIntelligenceManager?.getMetadata?.();if(vm&&Number.isFinite(Number(vm.imageIntelCount))){const total=Number(vm.imageIntelCount)||0,available=Number(vm.imageIntelAvailableCount)||0,pending=Number(vm.imageIntelPendingCount)||0;out+=`Vision cache: ${available}/${total} image context item(s) analyzed${pending?`; ${pending} pending`:''}${vm.imageIntelErrors?.length?`; ${vm.imageIntelErrors.length} recent analysis error(s)`:''}\n`;}
        out+='Reasoning priority: current Owner request → latest explicit active-conversation corrections → earlier active-conversation requirements/commitments → active listing defaults → derived summaries. Keep Owner↔assistant dialogue distinct from Owner↔customer Etsy messages.\n';return out;
    }
    async function recordDetailFacts(data,ordering={}){const detail=data?.detail;if(!detail||!chrome.runtime?.id)return false;const live=liveConvo(),convoId=String(detail.conversation_id||'').trim();if(!live||convoId!==String(live))return false;const requestSequence=Number(ordering.requestSequence),ordered=Number.isFinite(requestSequence)&&requestSequence>=0,sessionId=window.EtsyContextInterceptor?.getSessionId?.()||null,existing=await readFacts(convoId);if(ordered&&sessionId&&existing?.sourceSessionId===sessionId&&Number(existing.sourceSequence||0)>requestSequence)return false;const receipt=detail.receipt_history?.[0]||null,facts={convoId,receiptId:receipt?.receipt_id?String(receipt.receipt_id):null,transactionIds:(receipt?.transactions||[]).map(x=>x?.transaction_id).filter(Boolean).map(String),updatedAt:Date.now()};if(ordered&&sessionId){facts.sourceSessionId=sessionId;facts.sourceSequence=requestSequence;}await writeFacts(facts);return true;}
    window.addEventListener('message',event=>{if(event.source!==window||event.data?.source!=='etsy-page-interceptor'||event.data?.type!=='ETSY_DETAIL_VIEW_DATA')return;recordDetailFacts(event.data.data,{requestSequence:event.data.requestSequence,requestStartedAt:event.data.requestStartedAt}).catch(e=>console.debug('AgentContext: detail facts update failed',e?.message||e));});
    const instructions=BaseAIService.INSTRUCTIONS,originalBuild=instructions.buildFullInstruction;instructions.buildFullInstruction=async function(context){const[base,snapshot]=await Promise.all([originalBuild.call(this,context),buildActiveContextSnapshot()]);if(!snapshot)return base;const i=base.lastIndexOf('\n\n[PAGE_SCOPE:');return i===-1?`${base}${snapshot}`:`${base.slice(0,i)}${snapshot}${base.slice(i)}`;};
    BaseAIService.prototype.buildConversationHistory=async function(userId,currentUserMessage){const key=userId&&String(userId).startsWith('current_chat_messages')?String(userId):'current_chat_messages',messages=[];try{const s=await chrome.storage.local.get([key]),all=(s[key]||[]).filter(m=>m?.type==='user'||m?.type==='ai'),history=all.length<=MAX_ASSISTANT_HISTORY_MESSAGES?all:[...all.slice(0,FIRST_ASSISTANT_HISTORY_MESSAGES),...all.slice(-(MAX_ASSISTANT_HISTORY_MESSAGES-FIRST_ASSISTANT_HISTORY_MESSAGES))];for(const m of history)messages.push({role:m.type==='user'?'user':'assistant',content:this.trimMessageText(m.text,MAX_ASSISTANT_MESSAGE_CHARS)});}catch(e){console.warn('AgentContext: assistant history read failed',e);}const current=this.trimMessageText(currentUserMessage,MAX_ASSISTANT_MESSAGE_CHARS),last=messages[messages.length-1];if(!last||last.role!=='user'||last.content!==current)messages.push({role:'user',content:current});return messages;};
    window.AgentContextManager={ACTIVE_FACTS_KEY,MAX_ASSISTANT_HISTORY_MESSAGES,buildActiveContextSnapshot,recordDetailFacts,enrichDetailViewData:recordDetailFacts};
})();
