// agent_scoped_context_bridge.js - Makes BaseAIService consume per-conversation Etsy context.
(() => {
    'use strict';
    const instructions=window.BaseAIService?.INSTRUCTIONS,store=window.ScopedConversationStore;
    if(!instructions||!store||instructions.__etsyScopedContextBridge)return;
    const liveConvoId=()=>location.pathname.match(/^\/messages\/(\d+)/)?.[1]||null;
    async function waitForHistory(convoId,timeoutMs=1500){const started=Date.now();while(Date.now()-started<timeoutMs){const h=await store.getHistory(convoId);if(h?.messages?.length&&String(h.convo_id||'')===String(convoId))return true;await new Promise(r=>setTimeout(r,150));}return false;}
    async function waitForListing(timeoutMs=1500){const convoId=liveConvoId();if(!convoId)return false;const started=Date.now();while(Date.now()-started<timeoutMs){const listing=await store.getListing(convoId);if(listing?.listingId){const key=`RAG_LISTING_${listing.listingId}`,cached=await chrome.storage.local.get([key]);if(cached[key]?.title)return true;}await new Promise(r=>setTimeout(r,200));}return false;}
    instructions.waitForChatHistory=waitForHistory;
    instructions.waitForListingContext=waitForListing;

    instructions.getChatHistoryContext=async function(){
        try{
            const convoId=liveConvoId();if(!convoId||!chrome.runtime?.id)return'';let history=await store.getHistory(convoId);if(!history?.messages?.length){await waitForHistory(convoId,1500);history=await store.getHistory(convoId);}if(!history?.messages?.length||String(history.convo_id||'')!==String(convoId))return'';
            const age=Math.max(0,Date.now()-Number(history.timestamp||0));let context=`\n\n### CUSTOMER_CONVERSATION_HISTORY [CONTEXT_AGE: ${this.formatAge(age)}]:\n(Messages between the Owner and the customer, oldest → newest.)\n\n`;
            const candidates=history.messages,sizes=candidates.map(m=>Math.min(String(m.message_body||m.message||m.body||m.text||'').length,this.LIMITS.etsyChatMessageChars)),full=sizes.reduce((a,b)=>a+b,0);let indexes=candidates.map((_,i)=>i);
            if(full>this.LIMITS.etsyChatTotalChars){const begin=Math.floor(this.LIMITS.etsyChatTotalChars*.35),recent=this.LIMITS.etsyChatTotalChars-begin,selected=new Set();let used=0;for(let i=0;i<candidates.length;i++){if(selected.size&&used+sizes[i]>begin)break;selected.add(i);used+=sizes[i];}used=0;for(let i=candidates.length-1;i>=0;i--){if(selected.has(i))continue;if(used&&used+sizes[i]>recent)break;selected.add(i);used+=sizes[i];}indexes=[...selected].sort((a,b)=>a-b);}
            const omittedCount=candidates.length-indexes.length;if(omittedCount>0){context+=`[${omittedCount} middle message(s) omitted because the conversation exceeded the safety budget; beginning and newest messages are included.]\n\n`;if(window.ConversationContextManager){const selected=new Set(indexes),omitted=candidates.map((message,sourceIndex)=>({message,sourceIndex})).filter(item=>!selected.has(item.sourceIndex)),summary=await window.ConversationContextManager.getOrCreateSummary(history,omitted);context+=window.ConversationContextManager.buildContextSection(summary,omittedCount);}}
            for(const index of indexes){const m=candidates[index],senderId=String(m.sender_user_id||m.sender_id||m.user_id||'').trim(),customerId=String(history.customer_user_id||'').trim(),roleText=`${m.sender_type||''} ${m.role||''} ${m.author_role||''}`.toLowerCase(),role=customerId&&senderId?(customerId===senderId?'CUSTOMER':'OWNER'):/buyer|customer/.test(roleText)?'CUSTOMER':/seller|shop|owner|merchant/.test(roleText)?'OWNER':'PARTICIPANT',sender=m.sender_display_name||`User ${senderId||'unknown'}`,text=this.trimText(m.message_body||m.message||m.body||m.text||'',this.LIMITS.etsyChatMessageChars),n=Number(m.create_date),date=Number.isFinite(n)&&n>0?new Date(n<10_000_000_000?n*1000:n).toLocaleString():'';context+=`[${role}: ${sender}]${date?` (${date})`:''}: ${text}\n`;const attachments=Array.isArray(m.attachments)?m.attachments.length:Array.isArray(m.images)?m.images.length:(m.has_images?1:0);if(attachments)context+=`  📎 ${attachments} attachment(s)\n`;}
            const domImages=document.querySelectorAll('.quick-refunds-message-images a[href], .quick-refunds-message-images img[src]').length;if(domImages)context+=`\n[VISIBLE_CONVERSATION_ATTACHMENTS: ${domImages} image element(s) visible. Speaker/message association may be incomplete; use structured history and Vision summaries when available.]\n`;return context;
        }catch(error){console.warn('ScopedContextBridge: conversation context failed',error);return'';}
    };

    instructions.getRAGContext=async function(){
        try{
            const path=location.pathname,convoId=path.match(/^\/messages\/(\d+)/)?.[1]||null,editorId=path.match(/^\/your\/shops\/me\/listing-editor\/edit\/(\d+)/)?.[1]||null,publicId=path.match(/^\/listing\/(\d+)/)?.[1]||null;if(!convoId&&!editorId&&!publicId)return'';
            const primaryIds=[],secondaryIds=[];if(editorId)primaryIds.push(editorId);else if(publicId)primaryIds.push(publicId);else{let listing=await store.getListing(convoId);if(!listing?.listingId){await waitForListing(1500);listing=await store.getListing(convoId);}if(listing?.listingId)primaryIds.push(String(listing.listingId));}
            for(const url of this.scanCurrentChatForListings()){const id=url.match(/\/listing\/(\d+)/)?.[1];if(!id||primaryIds.includes(id)||secondaryIds.includes(id))continue;secondaryIds.push(id);}const allIds=[...primaryIds,...secondaryIds].slice(0,5);if(!allIds.length)return'';
            const keys=allIds.map(id=>`RAG_LISTING_${id}`),state=await chrome.storage.local.get(keys),now=Date.now(),TTL=24*60*60*1000,primary=[],secondary=[],expired=[];for(const id of allIds){const key=`RAG_LISTING_${id}`,cached=state[key];if(!cached?.title)continue;const ageMs=now-Number(cached.timestamp||0);if(ageMs>TTL){expired.push(key);continue;}(primaryIds.includes(id)?primary:secondary).push({id,cached,ageMs});}if(expired.length)chrome.storage.local.remove(expired);if(!primary.length&&!secondary.length)return'';
            let context='\n\n### PRODUCT_CONTEXT (cached listing data):\n';for(const {id,cached,ageMs} of primary){context+=`\n**[PRIMARY listing_id=${id}] ${cached.title}** (cached ${this.formatAge(ageMs)} ago)\n`;if(cached.personalization)context+=`Personalization field (buyer-facing): ${cached.personalization}\n`;if(cached.description)context+=`Description: ${this.trimText(cached.description,this.LIMITS.primaryListingDescriptionChars)}\n`;}if(secondary.length){context+='\n**Other listings mentioned on this page (summary only):**\n';for(const {id,cached} of secondary.slice(0,this.LIMITS.secondaryListings)){const snippet=this.trimText(String(cached.description||'').replace(/\s+/g,' '),this.LIMITS.secondarySnippetChars);context+=`- listing_id=${id} — "${cached.title}"${snippet?` — ${snippet}`:''}\n`;}}return context;
        }catch(error){console.warn('ScopedContextBridge: RAG context failed',error);return'';}
    };
    instructions.__etsyScopedContextBridge=true;
})();
