// chat_submission_guard.js
// Keeps typed submissions visually immediate and prevents internal diagnostics
// from leaking into the user-facing conversation UI.
(() => {
    'use strict';

    const OPTIMISTIC_ATTR = 'data-etsy-ai-optimistic';
    const OPTIMISTIC_TTL_MS = 30000;
    const DUPLICATE_GUARD_MS = 300;
    const optimisticEntries = [];
    let lastCapture = { text: '', at: 0 };

    const HIDDEN_SYSTEM_PATTERNS = [
        /^✅ API Keys Saved$/,
        /^⚠️ Please configure your .+ API Key to use this model\.$/,
        /^⚠️ Please configure at least one API Key in Settings\.$/,
        /^No AI diagnostics recorded yet\.$/,
        /^Copied \d+ AI diagnostic record\(s\)\.$/,
        /^AI diagnostics cleared\.$/,
        /^Configure the custom provider in the extension Settings page\.$/,
        /^Failed to copy diagnostics\./
    ];

    const SUBMISSION_REJECTED_PATTERNS = [
        /^This pre-upgrade chat is read-only /,
        /^⚠️ Extension error\. Please refresh the page\.$/,
        /^❌ Cannot open settings /,
        /^❌ Failed to load existing keys\./,
        /^❌ Failed to save API keys\./
    ];

    function normalizeText(value) {
        return String(value || '').replace(/\u00a0/g, ' ').replace(/\s+/g, ' ').trim();
    }

    function getComposerText() {
        return String(document.getElementById('user-input')?.innerText || '')
            .replace(/\u00a0/g, ' ')
            .trim();
    }

    function isGenerating() {
        const stopBtn = document.getElementById('stop-btn');
        return !!stopBtn && stopBtn.style.display !== 'none';
    }

    function getMessageText(messageEl) {
        if (!messageEl) return '';
        const clone = messageEl.cloneNode(true);
        clone.querySelectorAll('.etsy-ai-timestamp, button').forEach(el => el.remove());
        return normalizeText(clone.textContent);
    }

    function pruneOptimisticEntries() {
        const cutoff = Date.now() - OPTIMISTIC_TTL_MS;
        for (let i = optimisticEntries.length - 1; i >= 0; i -= 1) {
            const entry = optimisticEntries[i];
            if (!entry.element?.isConnected || entry.createdAt < cutoff) {
                entry.element?.removeAttribute?.(OPTIMISTIC_ATTR);
                optimisticEntries.splice(i, 1);
            }
        }
    }

    function createOptimisticMessage(text) {
        pruneOptimisticEntries();

        const now = Date.now();
        const normalizedText = normalizeText(text);
        if (normalizedText === lastCapture.text && now - lastCapture.at < DUPLICATE_GUARD_MS) return;
        lastCapture = { text: normalizedText, at: now };

        const chatBox = document.getElementById('chat-box');
        if (!chatBox) return;

        const div = document.createElement('div');
        div.className = 'etsy-ai-msg user';
        div.setAttribute(OPTIMISTIC_ATTR, '1');
        div.appendChild(document.createTextNode(text));

        const time = document.createElement('span');
        time.className = 'etsy-ai-timestamp';
        time.innerText = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
        div.appendChild(time);

        chatBox.appendChild(div);
        chatBox.scrollTop = chatBox.scrollHeight;
        optimisticEntries.push({ text: normalizedText, element: div, createdAt: now });
    }

    function captureSubmission() {
        const text = getComposerText();
        if (!text || isGenerating()) return;
        createOptimisticMessage(text);
    }

    function findMatchingOptimistic(text) {
        pruneOptimisticEntries();
        const normalized = normalizeText(text);
        for (let i = optimisticEntries.length - 1; i >= 0; i -= 1) {
            const entry = optimisticEntries[i];
            if (entry.text === normalized && entry.element?.isConnected) return { entry, index: i };
        }
        return null;
    }

    function reconcileOfficialUserMessage(messageEl) {
        if (!messageEl || messageEl.hasAttribute(OPTIMISTIC_ATTR)) return;
        const match = findMatchingOptimistic(getMessageText(messageEl));
        if (!match) return;

        // Keep the already-visible bubble and drop the delayed duplicate generated by chat_ui.js.
        match.entry.element.removeAttribute(OPTIMISTIC_ATTR);
        optimisticEntries.splice(match.index, 1);
        messageEl.remove();
    }

    function removeRejectedOptimisticMessage(systemText) {
        if (!SUBMISSION_REJECTED_PATTERNS.some(pattern => pattern.test(systemText))) return;

        const composerText = normalizeText(getComposerText());
        pruneOptimisticEntries();
        for (let i = optimisticEntries.length - 1; i >= 0; i -= 1) {
            const entry = optimisticEntries[i];
            if (!composerText || entry.text !== composerText) continue;
            entry.element?.remove();
            optimisticEntries.splice(i, 1);
            break;
        }
    }

    function sanitizeErrorMessage(messageEl) {
        if (!messageEl?.classList?.contains('error')) return;
        const content = messageEl.querySelector('.error-content');
        if (!content) return;

        const visible = String(content.innerText || '').split(/\n\s*\nTechnical:/i)[0].trim();
        if (visible) content.innerText = visible;
    }

    function sanitizeSystemMessage(messageEl) {
        if (!messageEl?.matches?.('.etsy-ai-msg.system')) return;
        sanitizeErrorMessage(messageEl);

        const text = getMessageText(messageEl);
        removeRejectedOptimisticMessage(text);

        if (HIDDEN_SYSTEM_PATTERNS.some(pattern => pattern.test(text))) {
            messageEl.remove();
        }
    }

    function sanitizeStatusText(root) {
        if (!root) return;
        const nodes = [];
        if (root.nodeType === Node.ELEMENT_NODE && root.matches?.('.etsy-ai-status-text')) nodes.push(root);
        if (root.querySelectorAll) nodes.push(...root.querySelectorAll('.etsy-ai-status-text'));
        nodes.forEach(node => node.remove());
    }

    function processAddedNode(node) {
        if (node.nodeType !== Node.ELEMENT_NODE) return;

        sanitizeStatusText(node);

        const userMessages = [];
        if (node.matches?.('.etsy-ai-msg.user')) userMessages.push(node);
        if (node.querySelectorAll) userMessages.push(...node.querySelectorAll('.etsy-ai-msg.user'));
        userMessages.forEach(reconcileOfficialUserMessage);

        const systemMessages = [];
        if (node.matches?.('.etsy-ai-msg.system')) systemMessages.push(node);
        if (node.querySelectorAll) systemMessages.push(...node.querySelectorAll('.etsy-ai-msg.system'));
        systemMessages.forEach(sanitizeSystemMessage);
    }

    document.addEventListener('keydown', event => {
        const input = event.target?.closest?.('#user-input');
        if (!input || event.key !== 'Enter' || event.shiftKey || event.isComposing) return;
        captureSubmission();
    }, true);

    document.addEventListener('click', event => {
        if (!event.target?.closest?.('#send-btn')) return;
        captureSubmission();
    }, true);

    const observer = new MutationObserver(mutations => {
        for (const mutation of mutations) {
            mutation.addedNodes.forEach(processAddedNode);
        }
        pruneOptimisticEntries();
    });

    observer.observe(document.documentElement, { childList: true, subtree: true });
    sanitizeStatusText(document);
    document.querySelectorAll('.etsy-ai-msg.system').forEach(sanitizeSystemMessage);
})();
