// etsy_context_interceptor.js - Live Etsy conversation ingestion with strict SPA/multi-tab scope guards.
window.EtsyContextInterceptor=(function(){
    const STORAGE_KEYS={SHOP_ID:'ETSY_GLOBAL_SHOP_ID',USER_ID:'ETSY_GLOBAL_USER_ID',CHAT_HISTORY:'ETSY_CHAT_HISTORY',CURRENT_LISTING_ID:'ETSY_CURRENT_LISTING_ID',CURRENT_LISTING_SCOPE:'ETSY_CURRENT_LISTING_SCOPE'};
    const store=window.ScopedConversationStore||null,CONTENT_SESSION_ID=`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`;
    let initialized=false,lastConvoId=null,messageListenerInstalled=false,navigationListenersInstalled=false,navigationGeneration=0,navigationTimer=null,cleanupQueue=Promise.resolve();
    const liveConvo=()=>window.location.pathname.match(/^\/messages\/(\d+)/)?.[1]||null;
    const id=v=>v===null||v===undefined?'':String(v).trim();
    const seq=v=>{const n=Number(v);return Number.isFinite(n)&&n>=0?n:0;};
    const liveMatches=c=>!!liveConvo()&&liveConvo()===id(c);
    function timeMs(m){const raw=m?.create_date??m?.created_at??m?.timestamp??null,n=Number(raw);if(raw!==null&&raw!==''&&Number.isFinite(n)&&n>0)return n<10_000_000_000?n*1000:n;const p=Date.parse(String(raw||''));return Number.isFinite(p)?p:0;}
    function attachmentId(a){return id(a?.convo_message_attachment_id||a?.attachment_id||a?.image_id||a?.url||a?.fullsize_url||a?.image_url||a?.download_url||a?.image_data?.url||a?.thumb_url||a?.thumbnail_url);}
    function mergeAttachments(m){const out=[],seen=new Set();for(const a of[...(m?.attachments||[]),...(m?.images||[])]){if(!a)continue;const key=attachmentId(a)||`index:${out.length}`;if(seen.has(key))continue;seen.add(key);out.push(a);}return out;}
    function normalizeMessages(messages){const out=(messages||[]).map(m=>({...m,attachments:mergeAttachments(m)}));if(out.length>1&&out.every(m=>timeMs(m)>0))out.sort((a,b)=>timeMs(a)-timeMs(b));return out;}
    function storedSequence(record,convoId){if(!record||id(record.convo_id||record.convoId)!==convoId||record.sourceSessionId!==CONTENT_SESSION_ID)return 0;return seq(record.sourceSequence);}
    async function readHistory(convoId){if(store)return store.getHistory(convoId);const s=await chrome.storage.local.get([STORAGE_KEYS.CHAT_HISTORY]),h=s[STORAGE_KEYS.CHAT_HISTORY];return id(h?.convo_id||h?.conversation_id)===id(convoId)?h:null;}
    async function writeHistory(history){if(store)return store.setHistory(history);await chrome.storage.local.set({[STORAGE_KEYS.CHAT_HISTORY]:history});return true;}
    async function readListing(convoId){if(store)return store.getListing(convoId);const s=await chrome.storage.local.get([STORAGE_KEYS.CURRENT_LISTING_ID,STORAGE_KEYS.CURRENT_LISTING_SCOPE]),listing=id(s[STORAGE_KEYS.CURRENT_LISTING_ID]),scope=s[STORAGE_KEYS.CURRENT_LISTING_SCOPE];return listing&&id(scope?.convoId)===id(convoId)&&id(scope?.listingId)===listing?{...scope,listingId:listing}:null;}
    async function writeListing(convoId,listingId,extra){if(store)return store.setListing(convoId,listingId,extra);const scope={...extra,convoId:String(convoId),listingId:String(listingId)};await chrome.storage.local.set({[STORAGE_KEYS.CURRENT_LISTING_ID]:String(listingId),[STORAGE_KEYS.CURRENT_LISTING_SCOPE]:scope});return true;}
    async function clearListing(convoId){if(store)return store.clearListing(convoId);await chrome.storage.local.remove([STORAGE_KEYS.CURRENT_LISTING_ID,STORAGE_KEYS.CURRENT_LISTING_SCOPE]);return true;}
    async function responseCurrent(convoId,sourceSequence){if(!liveMatches(convoId))return false;const[history,listing]=await Promise.all([readHistory(convoId),readListing(convoId)]);if(!liveMatches(convoId))return false;return seq(sourceSequence)>=Math.max(storedSequence(history,convoId),storedSequence(listing,convoId));}

    function setupMessageListener(){if(messageListenerInstalled)return;messageListenerInstalled=true;window.addEventListener('message',event=>{if(event.source!==window||event.data?.source!=='etsy-page-interceptor'||event.data?.type!=='ETSY_DETAIL_VIEW_DATA')return;handleDetail(event.data.data,{requestSequence:event.data.requestSequence,requestStartedAt:event.data.requestStartedAt}).catch(e=>console.error('EtsyContextInterceptor: detail processing failed',e));});}
    async function handleDetail(data,ordering={}){const detail=data?.detail;if(!detail)return false;return processDetail(detail,data?.shop_id||detail?.shop_id||null,ordering);}
    async function processDetail(detail,shopId,ordering={}){
        const convoId=id(detail?.conversation_id);if(!convoId||!liveMatches(convoId)||!chrome.runtime?.id)return false;lastConvoId=convoId;const timestamp=Date.now(),sourceSequence=seq(ordering.requestSequence),receiptHistory=Array.isArray(detail.receipt_history)?detail.receipt_history:[],receiptId=receiptHistory[0]?.receipt_id;let messages=Array.isArray(detail.messages)?detail.messages:[];
        if(shopId)await updateGlobal(STORAGE_KEYS.SHOP_ID,String(shopId));
        if(receiptId&&shopId){const mission=await fetchMission(shopId,receiptId);if(!(await responseCurrent(convoId,sourceSequence)))return false;if(mission.length)messages=mission;}
        if(messages.length&&await responseCurrent(convoId,sourceSequence)){await writeHistory({convo_id:convoId,customer_display_name:String(detail.other_user?.display_name||'').trim(),customer_user_id:detail.other_user?.user_id?String(detail.other_user.user_id):null,messages:normalizeMessages(messages),timestamp,sourceSessionId:CONTENT_SESSION_ID,sourceSequence});window.ShopIntelligenceManager?.maybeBootstrap?.('conversation_loaded');}
        if(!(await responseCurrent(convoId,sourceSequence)))return false;
        let listingId=extractListingId(detail);const transactionId=receiptHistory[0]?.transactions?.[0]?.transaction_id;if(!listingId&&transactionId)listingId=await listingFromTransaction(transactionId);if(!(await responseCurrent(convoId,sourceSequence)))return false;
        if(listingId)await writeListing(convoId,String(listingId),{updatedAt:timestamp,sourceSessionId:CONTENT_SESSION_ID,sourceSequence});else await clearListing(convoId);
        if(!(await responseCurrent(convoId,sourceSequence)))return false;window.ImageIntelligenceManager?.scheduleBackgroundAnalysis?.(0);return true;
    }

    function enqueueCleanup(){const task=cleanupQueue.catch(()=>undefined).then(()=>clearStaleStorage());cleanupQueue=task.then(()=>undefined,()=>undefined);return task;}
    async function settleNavigation(generation){await enqueueCleanup();if(generation!==navigationGeneration)return;if(liveConvo())parseInitial().catch(e=>console.error('EtsyContextInterceptor: initial hydration failed',e));}
    function scheduleNavigation(delay=0){const generation=++navigationGeneration;if(navigationTimer)clearTimeout(navigationTimer);navigationTimer=setTimeout(()=>{navigationTimer=null;settleNavigation(generation).catch(e=>console.error('EtsyContextInterceptor: navigation sync failed',e));},Math.max(0,delay));}
    function setupNavigationListeners(){if(navigationListenersInstalled)return;navigationListenersInstalled=true;const fn=()=>scheduleNavigation(0);window.addEventListener('etsy-ai-locationchange',fn);window.addEventListener('popstate',fn);window.addEventListener('hashchange',fn);}
    function init(){if(!initialized){initialized=true;setupMessageListener();setupNavigationListeners();}scheduleNavigation(0);}
    async function fetchMission(shopId,receiptId){try{const response=await fetch(`https://www.etsy.com/api/v3/ajax/shop/${encodeURIComponent(shopId)}/mission-control/orders/convos/${encodeURIComponent(receiptId)}`,{credentials:'include',headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest'}});if(!response.ok)return[];const data=await response.json();return Array.isArray(data.messages)?data.messages:[];}catch(e){console.warn('EtsyContextInterceptor: mission-control failed',e);return[];}}

    async function clearStaleStorage(){
        // Per-conversation keys are the source of truth. Never let one tab delete another
        // tab's legacy compatibility mirror merely because their live convo IDs differ.
        if(store)return true;
        if(!chrome.runtime?.id)return false;const current=liveConvo();try{const first=await chrome.storage.local.get([STORAGE_KEYS.CHAT_HISTORY,STORAGE_KEYS.CURRENT_LISTING_ID,STORAGE_KEYS.CURRENT_LISTING_SCOPE]),remove=[];const h=first[STORAGE_KEYS.CHAT_HISTORY],listing=first[STORAGE_KEYS.CURRENT_LISTING_ID],scope=first[STORAGE_KEYS.CURRENT_LISTING_SCOPE];if(!current){if(h)remove.push(STORAGE_KEYS.CHAT_HISTORY);if(listing||scope)remove.push(STORAGE_KEYS.CURRENT_LISTING_ID,STORAGE_KEYS.CURRENT_LISTING_SCOPE);}else{if(h&&id(h.convo_id)!==current)remove.push(STORAGE_KEYS.CHAT_HISTORY);const match=scope&&id(scope.convoId)===current;if((listing&&!match)||(scope&&!match))remove.push(STORAGE_KEYS.CURRENT_LISTING_ID,STORAGE_KEYS.CURRENT_LISTING_SCOPE);}if(!remove.length||liveConvo()!==current)return true;const latest=await chrome.storage.local.get([STORAGE_KEYS.CHAT_HISTORY,STORAGE_KEYS.CURRENT_LISTING_ID,STORAGE_KEYS.CURRENT_LISTING_SCOPE]);if(liveConvo()!==current)return false;const safe=[];if(remove.includes(STORAGE_KEYS.CHAT_HISTORY)){const x=latest[STORAGE_KEYS.CHAT_HISTORY];if(!current?!!x:!!x&&id(x.convo_id)!==current)safe.push(STORAGE_KEYS.CHAT_HISTORY);}if(remove.includes(STORAGE_KEYS.CURRENT_LISTING_ID)||remove.includes(STORAGE_KEYS.CURRENT_LISTING_SCOPE)){const x=latest[STORAGE_KEYS.CURRENT_LISTING_ID],s=latest[STORAGE_KEYS.CURRENT_LISTING_SCOPE],match=s&&id(s.convoId)===current;if(!current?!!(x||s):!!((x&&!match)||(s&&!match)))safe.push(STORAGE_KEYS.CURRENT_LISTING_ID,STORAGE_KEYS.CURRENT_LISTING_SCOPE);}if(safe.length)await chrome.storage.local.remove([...new Set(safe)]);return true;}catch(e){console.warn('EtsyContextInterceptor: stale cleanup failed',e);return false;}}
    async function parseInitial(){if(!liveConvo())return false;try{const ctx=extractContext(),detail=ctx?.data?.initial_data?.detail;if(!detail||!liveMatches(detail.conversation_id))return false;return processDetail(detail,ctx?.data?.shop_id||detail?.shop_id||null,{requestSequence:0});}catch(e){console.warn('EtsyContextInterceptor: initial parse failed',e);return false;}}
    function balanced(text,start){let depth=0,quote='',escaped=false;for(let i=start;i<text.length;i++){const c=text[i];if(quote){if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c===quote)quote='';continue;}if(c==='"'||c==="'"){quote=c;continue;}if(c==='{')depth++;else if(c==='}'&&--depth===0)return text.slice(start,i+1);}return'';}
    function extractContext(){if(window.Etsy?.Context)return window.Etsy.Context;for(const script of document.querySelectorAll('script[type="text/javascript"], script:not([src])')){const text=script.textContent||'',marker=text.indexOf('Etsy.Context');if(marker<0)continue;const eq=text.indexOf('=',marker),start=eq>=0?text.indexOf('{',eq):-1;if(start<0)continue;const json=balanced(text,start);if(!json)continue;try{return JSON.parse(json);}catch(_){}}return null;}
    function normalizeListingId(v){const m=id(v).match(/\d{5,}/);return m?m[0]:null;}
    function extractListingId(detail){if(!detail)return null;for(const v of[detail.listing_id,detail.listingId,detail.listing?.listing_id,detail.listing?.listingId,detail.transaction?.listing_id,detail.transaction?.listingId,detail.receipt_history?.[0]?.transactions?.[0]?.listing_id,detail.receipt_history?.[0]?.transactions?.[0]?.listingId]){const x=normalizeListingId(v);if(x)return x;}const seen=new Set(),stack=[detail.receipt_history,detail.messages,detail.order,detail.receipt,detail.transaction];while(stack.length){const item=stack.pop();if(!item||typeof item!=='object'||seen.has(item))continue;seen.add(item);if(Array.isArray(item)){stack.push(...item);continue;}for(const[k,v]of Object.entries(item)){const lk=k.toLowerCase();if((lk==='listing_id'||lk==='listingid')&&v){const x=normalizeListingId(v);if(x)return x;}if(typeof v==='string'&&/listing/.test(lk+v)){const m=v.match(/\/listing\/(\d{5,})/);if(m)return m[1];}if(v&&typeof v==='object')stack.push(v);}}return null;}
    async function listingFromTransaction(transactionId){try{const response=await fetch(`https://www.etsy.com/transaction/${encodeURIComponent(transactionId)}`,{credentials:'include',redirect:'follow'});return response.url?.match(/\/listing\/(\d+)/)?.[1]||null;}catch(_){return null;}}
    async function updateGlobal(key,value){if(!chrome.runtime?.id)return;try{const s=await chrome.storage.local.get([key]);if(s[key]!==value)await chrome.storage.local.set({[key]:value});}catch(_){}}
    return{init,STORAGE_KEYS,getSessionId:()=>CONTENT_SESSION_ID,async getShopId(){const s=await chrome.storage.local.get([STORAGE_KEYS.SHOP_ID]);return s[STORAGE_KEYS.SHOP_ID]||null;},async getUserId(){const s=await chrome.storage.local.get([STORAGE_KEYS.USER_ID]);return s[STORAGE_KEYS.USER_ID]||null;},async getCurrentListingId(){const x=store?await store.getListing(liveConvo()):await readListing(liveConvo());return x?.listingId||null;},async getChatHistory(){const h=await readHistory(liveConvo());return h&&liveMatches(h.convo_id)?h:null;},getState:()=>({initialized,lastConvoId,sessionId:CONTENT_SESSION_ID,navigationGeneration,multiTabScoped:!!store})};
})();
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>window.EtsyContextInterceptor.init());else window.EtsyContextInterceptor.init();
